# Generated by Django 5.1 on 2024-09-09 18:40

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('sellingitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.sellingitem')),
                ('exp_date', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('ssn', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cards.sellingitem',),
        ),
        migrations.CreateModel(
            name='SelfAccount',
            fields=[
                ('sellingitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.sellingitem')),
                ('account_type', models.CharField(max_length=255)),
                ('account_url', models.CharField(max_length=255)),
                ('proof', models.ImageField(upload_to='cards/static/images/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            bases=('cards.sellingitem',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.sellingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.sellingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='started', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='HQCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('base', models.CharField(max_length=200)),
                ('card_bin', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('visa', 'Visa'), ('master_card', 'Master Card')], default='visa', max_length=20)),
                ('level', models.CharField(choices=[('standard', 'STANDARD'), ('gold', 'GOLD'), ('classic', 'CLASSIC'), ('prepaid', 'PREPAID'), ('infinite', 'INFINITE')], default='standard', max_length=20)),
                ('credit_debit', models.CharField(choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], default='credit', max_length=10)),
                ('card_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('ua', models.CharField(blank=True, max_length=200, null=True)),
                ('refundable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cards.card',),
        ),
        migrations.CreateModel(
            name='WholesaleCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.card')),
                ('number', models.CharField(max_length=16)),
                ('quantity', models.IntegerField()),
                ('user_agents', models.TextField()),
                ('cvv', models.CharField(max_length=3)),
            ],
            bases=('cards.card',),
        ),
        migrations.CreateModel(
            name='DumpCard',
            fields=[
                ('hqcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.hqcard')),
                ('track1', models.CharField(blank=True, max_length=10, null=True)),
                ('track2', models.CharField(blank=True, max_length=10, null=True)),
            ],
            bases=('cards.hqcard',),
        ),
        migrations.CreateModel(
            name='VHQCard',
            fields=[
                ('hqcard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.hqcard')),
                ('months_left', models.IntegerField()),
                ('screen_resolution', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.TextField()),
            ],
            bases=('cards.hqcard',),
        ),
    ]
