# Generated by Django 5.1 on 2024-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='crypto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
