# Generated by Django 5.1 on 2024-09-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_payment_crypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('check', 'Check'), ('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed')], default='check', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
